spring.datasource.url=jdbc:postgresql://localhost:5433/api_poc_sobrevidas_db
spring.datasource.username=tiago
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true